Repository catenax-ng/product-portal-backend, pull requests merged in 2022-07, with the labels that each got.

#91 CPLP-1087 add swagger documentation
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/CatenaX.NetworkServices.Administration.Service.csproj
  src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ConnectorsController.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/DocumentsController.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/InvitationController.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/RegistrationController.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/ServiceAccountController.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Program.cs
  src/framework/CatenaX.NetworkServices.Framework.Swagger/AddAuthFilter.cs
  src/framework/CatenaX.NetworkServices.Framework.Swagger/BaseStatusCodeFilter.cs
  src/framework/CatenaX.NetworkServices.Framework.Swagger/CatenaX.NetworkServices.Framework.Swagger.csproj
  src/framework/CatenaX.NetworkServices.Framework.Swagger/SwaggerGenConfiguration.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/CatenaX.NetworkServices.App.Service.csproj
  src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/Program.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/CatenaX.NetworkServices.PortalBackend.DBAccess.csproj
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/CatenaX.NetworkServices.Provisioning.Service.csproj
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/Controllers/ClientController.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/Controllers/IdentityProviderController.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/Program.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/CatenaX.NetworkServices.Registration.Service.csproj
  src/registration/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/Program.cs
  tests/administration/CatenaX.NetworkServices.Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Labels: documentation, enhancement

#107 CPLP-1120 refactor app business logic
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/IUserBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Controllers/UserController.cs
  src/framework/CatenaX.NetworkServices.Framework.Models/CatenaX.NetworkServices.Framework.Models.csproj
  src/framework/CatenaX.NetworkServices.Framework.Models/Constants.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/IAppsBusinessLogic.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/Program.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/ViewModels/AppCompanySubscriptionStatusViewModel.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/ViewModels/AppDetailsViewModel.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/ViewModels/AppSubscriptionStatusViewModel.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/ViewModels/AppViewModel.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/ViewModels/BusinessAppViewModel.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/ViewModels/CompanySubscriptionStatusViewModel.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/IPortalRepositories.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AppCompanySubscriptionStatusData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AppData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AppDetailsData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AppWithSubscriptionStatus.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/BusinessAppData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanySubscriptionStatusData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/PortalRepositories.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppUserRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IAppRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IAppUserRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ICompanyAssignedAppsRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IUserRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/UserRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/App.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/Company.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/CompanyAssignedApp.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/PortalDbContext.cs
  tests/marketplace/CatenaX.NetworkServices.App.Service.Tests/AppBusinessLogicTests.cs
  tests/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests/AppRepositoryTests.cs
  tests/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests.csproj
  tests/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
Labels: enhancement

#125 CPLP-1041 fix doc upload
  src/framework/CatenaX.NetworkServices.Framework.Swagger/SwaggerGenConfiguration.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs
Labels: bug

#127 CPLP 1189 - get app details
  src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/AppsBusinessLogic.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/BusinessLogic/IAppsBusinessLogic.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AppDetailsData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AppProviderDetailsData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/CompanyAssignedAppsRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/IAppRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ICompanyAssignedAppsRepository.cs
  tests/marketplace/CatenaX.NetworkServices.App.Service.Tests/AppBusinessLogicTests.cs
  tests/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests/AppRepositoryTests.cs
Labels: enhancement

#130 CPLP-1281 remove unused usings
  keycloak/src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs
  keycloak/src/Keycloak.Net/Clients/KeycloakClient.cs
  keycloak/src/Keycloak.Net/Models/OpenIDConfiguration/OpenIDConfiguration.cs
  keycloak/src/Keycloak.Net/Models/Users/User.cs
  keycloak/src/Keycloak.Net/Models/Users/UserConsent.cs
  keycloak/src/Keycloak.Net/Users/KeycloakClient.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/BusinessLogic/UserBusinessLogic.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Models/UserRoleInfo.cs
  src/administration/CatenaX.NetworkServices.Administration.Service/Models/UserUpdateInfo.cs
  src/framework/CatenaX.NetworkServices.Framework.DBAccess/DBConnectionSettings.cs
  src/keycloak/CatenaX.NetworkServices.Keycloak.Authentication/ClaimRequestPathHandler.cs
  src/keycloak/CatenaX.NetworkServices.Keycloak.Authentication/KeycloakClaimsTransformation.cs
  src/mailing/CatenaX.NetworkServices.Mailing.SendMail/IMailingService.cs
  src/mailing/CatenaX.NetworkServices.Mailing.SendMail/ISendMail.cs
  src/mailing/CatenaX.NetworkServices.Mailing.SendMail/MailingService.cs
  src/mailing/CatenaX.NetworkServices.Mailing.SendMail/SendMail.cs
  src/mailing/CatenaX.NetworkServices.Mailing.Template/Attributes/PathAttribute.cs
  src/mailing/CatenaX.NetworkServices.Mailing.Template/ITemplateManager.cs
  src/mailing/CatenaX.NetworkServices.Mailing.Template/NoSuchTemplateException.cs
  src/mailing/CatenaX.NetworkServices.Mailing.Template/TemplateManager.cs
  src/mailing/CatenaX.NetworkServices.Mailing.Template/TemplateSettings.cs
  src/marketplace/CatenaX.NetworkServices.App.Service/Controllers/AppsController.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AgreementData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/AgreementsAssingedCompanyRoleData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyApplicationWithStatus.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyIamUser.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyRoleAgreementConsents.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Models/CompanyRoleData.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/AppRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess/Repositories/ConsentRepository.cs
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.PortalEntities/Entities/Document.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.DBAccess/ProvisioningDBAccess.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/ClientManager.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/IdentityProviderManager.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/OpenIDConfigurationManager.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/RealmManager.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/ServiceAccountManager.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Library/Extensions/UserManager.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Mail/IUserEmail.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Mail/UserEmail.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.ProvisioningEntities/Entities/UserPasswordReset.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/BusinessLogic/ClientBusinessLogic.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/BusinessLogic/IClientBusinessLogic.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/BusinessLogic/IIdentityProviderBussinessLogic.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/Controllers/ClientController.cs
  src/provisioning/CatenaX.NetworkServices.Provisioning.Service/Controllers/IdentityProviderController.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/BPN/BPNAccess.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/BPN/IBPNAccess.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/BPN/Model/FetchBusinessPartnerDto.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/BPN/Model/PaginatedFetchBusinessPartner.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/Model/CompanyRoleAgreementData.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/Model/InvitedUser.cs
  src/registration/CatenaX.NetworkServices.Registration.Service/RegistrationAccess/RegistrationDBAccess.cs
  tests/administration/CatenaX.NetworkServices.Administration.Service.Tests/Controllers/RegistrationControllerTest.cs
  tests/marketplace/CatenaX.NetworkServices.App.Service.Tests/AppBusinessLogicTests.cs
  tests/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests/PortalBackendDBAccessTest.cs
  tests/portalbackend/CatenaX.NetworkServices.PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
Labels: enhancement

#138 CPLP-1281: Sonarcloud enabling - add test coverage and exclude migrations project
  .github/workflows/sonarcloud.yml
  src/portalbackend/CatenaX.NetworkServices.PortalBackend.Migrations/CatenaX.NetworkServices.PortalBackend.Migrations.csproj
Labels: enhancement

#140 CPLP-1281: Sonarcloud - enable test-coverage
  .github/workflows/sonarcloud.yml
Labels: enhancement

#144 CPLP-1281: Add unit test execution workflow
  .github/workflows/unit.tests.yml
Labels: enhancement
