Repository catenax-ng/product-portal-backend, pull requests merged in 2022-11, with the labels that each got.

#301 CPLP-v0.7.0-ChangeLog-creation
  CHANGELOG.md
Labels: Prio Ticket

#302 Fix Provisioning Service
  src/provisioning/Provisioning.Service/Program.cs
Labels: bug, Prio Ticket

#309 CPLP-Fix-Registration-Get-Document-Auth-Role
  src/registration/Registration.Service/Controllers/RegistrationController.cs
Labels: Bug Fix

#294 CPLP-1716 subscription
  src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
  src/marketplace/Apps.Service/Controllers/AppsController.cs
  src/marketplace/Offers.Library/Service/IOfferService.cs
  src/marketplace/Offers.Library/Service/IOfferSubscriptionService.cs
  src/marketplace/Offers.Library/Service/OfferService.cs
  src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
  src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
  src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
  src/marketplace/Services.Service/Controllers/ServicesController.cs
  src/portalbackend/PortalBackend.DBAccess/Models/OfferingData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/AgreementRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IAgreementRepository.cs
  tests/marketplace/Apps.Service.Tests/Apps.Service.Tests.csproj
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
  tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
  tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
  tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/AgreementRepositoryTests.cs
Labels: enhancement

#296 CPLP-734-getowncompanyuser-excludedeletestatus
  src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/UserSettings.cs
  src/administration/Administration.Service/appsettings.json
  src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
Labels: Bug Fix

#310 username set for service activation mail
  src/marketplace/Offers.Library/Service/OfferService.cs
  src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
Labels: bug

#312 CPLP-1462: switch adminservice invite-new-user template to PortalNewUserWelcome
  src/administration/Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
  src/administration/Administration.Service/appsettings.json
  src/provisioning/Provisioning.Library/Models/UserCreationInfo.cs
  src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
  src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/registration/Registration.Service/Controllers/RegistrationController.cs
  tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Labels: Bug Fix

#318 CPLP-1634 fix get endpoint
  src/framework/Framework.Models/Pagination.cs
  src/notification/Notification.Service/BusinessLogic/INotificationBusinessLogic.cs
  src/notification/Notification.Service/BusinessLogic/NotificationBusinessLogic.cs
  src/notification/Notification.Service/BusinessLogic/NotificationSettings.cs
  src/notification/Notification.Service/Controllers/NotificationController.cs
  src/notification/Notification.Service/Program.cs
  src/notification/Notification.Service/appsettings.json
  src/portalbackend/PortalBackend.DBAccess/Models/NotificationSorting.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
  src/portalbackend/PortalBackend.PortalEntities/Entities/Notification.cs
  src/portalbackend/PortalBackend.PortalEntities/Entities/NotificationType.cs
  tests/notification/Notification.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
  tests/notification/Notification.Service.Tests/Controllers/NotificationControllerTest.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
Labels: bug, Bug Fix

#328 CPLP-1745 endpoint cleanup
  src/marketplace/Apps.Service/Controllers/AppsController.cs
  src/marketplace/Services.Service/Controllers/ServicesController.cs
  tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
  tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
Labels: enhancement

#329 CPLP-1501 add user status filter
  src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/UserRepositoryTests.cs
  tests/shared/Tests.Shared/TestSeeds/BaseSeed.cs
Labels: bug, enhancement

#337 CPLP-1812 change bpn claim to lowercase
  src/administration/Administration.Service/appsettings.json
  src/marketplace/Services.Service/appsettings.json
Labels: Bug Fix

#334 CPLP-1163 add service provider detail enabled for sa
  src/administration/Administration.Service/BusinessLogic/ServiceProviderBusinessLogic.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/ServiceProviderBusinessLogicTest.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRespotitoryTests.cs
Labels: bug

#343 CPLP-1806 change update service to put
  src/marketplace/Services.Service/Controllers/ServicesController.cs
Labels: Bug Fix

#347 bugfix/TEST-174-invite-email-shows-uuid
  src/mailing/Mailing.Template/EmailTemplates/additional_user_invitation.html
  src/mailing/Mailing.Template/EmailTemplates/additional_user_invitation_with_message.html
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityProviderRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
  src/provisioning/Provisioning.Library/Service/IUserProvisioningService.cs
  src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
  src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
  tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceAuxiliaryMethodsTests.cs
  tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Labels: Bug Fix

#350 CPLP-1766 provider can be updated
  .github/workflows/administration-service.yml
  .github/workflows/marketplace-app-service.yml
  .github/workflows/notification-service.yml
  .github/workflows/services-service.yml
  .github/workflows/veracode.yaml
  docker/Dockerfile-notification-service
  src/Portal.Backend.sln
  src/administration/Administration.Service/Administration.Service.csproj
  src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/administration/Administration.Service/Program.cs
  src/marketplace/Apps.Service/Apps.Service.csproj
  src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
  src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
  src/marketplace/Apps.Service/Program.cs
  src/marketplace/Offers.Library/Offers.Library.csproj
  src/marketplace/Offers.Library/Service/OfferService.cs
  src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
  src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
  src/marketplace/Services.Service/Program.cs
  src/notifications/Notifications.Library/INotificationService.cs
  src/notifications/Notifications.Library/NotificationService.cs
  src/notifications/Notifications.Library/Notifications.Library.csproj
  src/notifications/Notifications.Service/BusinessLogic/INotificationBusinessLogic.cs
  src/notifications/Notifications.Service/BusinessLogic/NotificationBusinessLogic.cs
  src/notifications/Notifications.Service/BusinessLogic/NotificationSettings.cs
  src/notifications/Notifications.Service/Controllers/NotificationController.cs
  src/notifications/Notifications.Service/Notifications.Service.csproj
  src/notifications/Notifications.Service/Program.cs
  src/notifications/Notifications.Service/Properties/launchSettings.json
  src/notifications/Notifications.Service/appsettings.json
  src/portalbackend/PortalBackend.DBAccess/Models/AppUpdateData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/INotificationRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
  tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
  tests/notifications/Notifications.Library.Tests/NotificationServiceTests.cs
  tests/notifications/Notifications.Library.Tests/Notifications.Library.Tests.csproj
  tests/notifications/Notifications.Service.Tests/BusinessLogic/NotificationBusinessLogicTests.cs
  tests/notifications/Notifications.Service.Tests/Controllers/NotificationControllerTest.cs
  tests/notifications/Notifications.Service.Tests/EnpointSetup/NotificationEndpoints.cs
  tests/notifications/Notifications.Service.Tests/IntegrationTests/NotificationControllerIntegrationTests.cs
  tests/notifications/Notifications.Service.Tests/Notifications.Service.Tests.csproj
  tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRespotitoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
Labels: bug, Bug Fix
